services:
  api:
    build: ./api
    image: linkextractor-api:step5-python
    ports:
      - "5000:80"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - my_network
    volumes:
      - ./shared_data:/shared_data

  redis:
    image: redis
    networks:
      - my_network
